#!/usr/bin/env bash
# commit_report.sh — Stage and commit the latest monthly journal to nocturnal branch.
# Run from repo root after /monthly_report generates the file.
#
# Usage:
#   ./commit_report.sh           # commits most recent report in reports/
#   ./commit_report.sh 2026-06   # commits a specific month

set -euo pipefail

REPORTS_DIR="$(dirname "$0")/reports"
JOURNAL_DIR="$(dirname "$0")/docs/journal"
mkdir -p "$JOURNAL_DIR"

if [ -n "${1:-}" ]; then
    MONTH="$1"
else
    # Find the most recently modified report
    MONTH=$(ls -t "$REPORTS_DIR"/*.md 2>/dev/null | head -1 | xargs basename | sed 's/\.md//')
fi

if [ -z "$MONTH" ]; then
    echo "No report found in $REPORTS_DIR. Run /monthly_report in Telegram first."
    exit 1
fi

SRC="$REPORTS_DIR/$MONTH.md"
DST="$JOURNAL_DIR/$MONTH.md"

if [ ! -f "$SRC" ]; then
    echo "Report not found: $SRC"
    exit 1
fi

cp "$SRC" "$DST"
git add "$DST"
git commit -m "journal: $MONTH trading progress

Auto-generated by Nox heartbeat monitor.
Branch: nocturnal | Engine: Alpaca paper → IBKR (pending)"

echo "✅ Committed $MONTH journal to nocturnal branch."
echo "   Push with: git push origin nocturnal"
